version: '2.0'
services:
  db:
    image: postgres:12
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: tourneyman
      POSTGRES_PASSWORD: password
  api:
    depends_on:
      - db
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
