"""Added base models

Revision ID: 9691ef1b1919
Revises: f289bbd3a6ec
Create Date: 2021-02-20 20:19:43.800962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9691ef1b1919'
down_revision = 'f289bbd3a6ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competitor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('organization', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.CheckConstraint('last_name IS NOT NULL OR organization IS NOT NULL'),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournament.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competitor_id'), 'competitor', ['id'], unique=False)
    op.create_table('stage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.CheckConstraint('status IN (0,1,2)', name='valid_status'),
    sa.CheckConstraint('type IN (0,1,2)', name='valid_type'),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournament.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stage_id'), 'stage', ['id'], unique=False)
    op.create_table('pool',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('stage_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['stage_id'], ['stage.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pool_id'), 'pool', ['id'], unique=False)
    op.create_table('match',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pool_id', sa.Integer(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('competitor_1_id', sa.Integer(), nullable=True),
    sa.Column('competitor_1_score', sa.Integer(), nullable=True),
    sa.Column('competitor_2_id', sa.Integer(), nullable=True),
    sa.Column('competitor_2_score', sa.Integer(), nullable=True),
    sa.Column('next_match_id', sa.Integer(), nullable=True),
    sa.Column('next_match_competitor_slot', sa.Integer(), nullable=True),
    sa.CheckConstraint('status IN (0,1,2)', name='valid_status'),
    sa.ForeignKeyConstraint(['competitor_1_id'], ['competitor.id'], ),
    sa.ForeignKeyConstraint(['competitor_2_id'], ['competitor.id'], ),
    sa.ForeignKeyConstraint(['next_match_id'], ['match.id'], ),
    sa.ForeignKeyConstraint(['pool_id'], ['pool.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_id'), 'match', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_match_id'), table_name='match')
    op.drop_table('match')
    op.drop_index(op.f('ix_pool_id'), table_name='pool')
    op.drop_table('pool')
    op.drop_index(op.f('ix_stage_id'), table_name='stage')
    op.drop_table('stage')
    op.drop_index(op.f('ix_competitor_id'), table_name='competitor')
    op.drop_table('competitor')
    # ### end Alembic commands ###
